menu:
    Blog: /
    Archive: /archives/
    #Tags: /tags 
    Twitter: https://twitter.com/Saeratom
    GitHub: https://github.com/SharerMax
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
google-analytics:
ga: UA-122964612-1

# Copyright Infomation
startyear: 2016
